<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Random Forest Classification with ggRandomForests • ggRandomForests</title>
<script src="../lightswitch.js"></script><script src="../deps/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="../deps/bootstrap-5.3.8/bootstrap.min.css" rel="stylesheet">
<script src="../deps/bootstrap-5.3.8/bootstrap.bundle.min.js"></script><link href="../deps/Outfit-0.4.10/font.css" rel="stylesheet">
<link href="../deps/Fira_Code-0.4.10/font.css" rel="stylesheet">
<link href="../deps/font-awesome-6.5.2/css/all.min.css" rel="stylesheet">
<link href="../deps/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet">
<script src="../deps/headroom-0.11.0/headroom.min.js"></script><script src="../deps/headroom-0.11.0/jQuery.headroom.min.js"></script><script src="../deps/bootstrap-toc-1.0.1/bootstrap-toc.min.js"></script><script src="../deps/clipboard.js-2.0.11/clipboard.min.js"></script><script src="../deps/search-1.0.0/autocomplete.jquery.min.js"></script><script src="../deps/search-1.0.0/fuse.min.js"></script><script src="../deps/search-1.0.0/mark.min.js"></script><script src="ggRandomForests-classification_files/libs/quarto-html/popper.min.js"></script><script src="ggRandomForests-classification_files/libs/quarto-html/tippy.umd.min.js"></script><link href="ggRandomForests-classification_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ggRandomForests-classification_files/libs/quarto-html/light-border.css" rel="stylesheet">
<!-- pkgdown --><script src="../pkgdown.js"></script><meta property="og:title" content="Random Forest Classification with ggRandomForests">
</head>
<body>
    <a href="#main" class="visually-hidden-focusable">Skip to contents</a>


    <nav class="navbar navbar-expand-lg fixed-top " aria-label="Site navigation"><div class="container">

    <a class="navbar-brand me-2" href="../index.html">ggRandomForests</a>

    <small class="nav-text text-muted me-auto" data-bs-toggle="tooltip" data-bs-placement="bottom" title="">3.5.0</small>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbar" class="collapse navbar-collapse ms-3">
      <ul class="navbar-nav me-auto">
<li class="nav-item"><a class="nav-link" href="../articles/ggRandomForests.html">Get started</a></li>
<li class="nav-item"><a class="nav-link" href="../reference/index.html">Reference</a></li>
<li class="active nav-item dropdown">
  <button class="nav-link dropdown-toggle" type="button" id="dropdown-articles" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">Articles</button>
  <ul class="dropdown-menu" aria-labelledby="dropdown-articles">
<li><a class="dropdown-item" href="../articles/ggRandomForests.html">Get Started</a></li>
    <li><hr class="dropdown-divider"></li>
    <li><h6 class="dropdown-header" data-toc-skip>Tutorials</h6></li>
    <li><a class="dropdown-item" href="../articles/ggRandomForests-survival.html">Random Forest Survival Analysis</a></li>
    <li><a class="dropdown-item" href="../articles/ggRandomForests-regression.html">Random Forest Regression</a></li>
    <li><a class="dropdown-item" href="../articles/ggRandomForests-classification.html">Random Forest Classification</a></li>
    <li><a class="dropdown-item" href="../articles/varpro.html">Exploring variable importance with varPro</a></li>
    <li><a class="dropdown-item" href="../articles/uvarpro.html">Variable selection without an outcome: unsupervised varPro</a></li>
  </ul>
</li>
<li class="nav-item dropdown">
  <button class="nav-link dropdown-toggle" type="button" id="dropdown-news" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">News</button>
  <ul class="dropdown-menu" aria-labelledby="dropdown-news">
<li><h6 class="dropdown-header" data-toc-skip>Releases</h6></li>
    <li><a class="external-link dropdown-item" href="https://github.com/ehrlinger/ggRandomForests/blob/main/NEWS.md">Version 2.6</a></li>
    <li><hr class="dropdown-divider"></li>
    <li><a class="dropdown-item" href="../news/index.html">Changelog</a></li>
  </ul>
</li>
      </ul>
<ul class="navbar-nav">
<li class="nav-item"><form class="form-inline" role="search">
 <input class="form-control" type="search" name="search-input" id="search-input" autocomplete="off" aria-label="Search site" placeholder="Search for" data-search-index="../search.json">
</form></li>
<li class="nav-item"><a class="external-link nav-link" href="https://github.com/ehrlinger/ggRandomForests/" aria-label="GitHub"><span class="fa fab fa-github fa-lg"></span></a></li>
<li class="nav-item"><a class="external-link nav-link" href="https://www.linkedin.com/in/ehrlinger/" aria-label="LinkedIn"><span class="fa fa-linkedin"></span></a></li>
<li class="nav-item dropdown">
  <button class="nav-link dropdown-toggle" type="button" id="dropdown-lightswitch" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true" aria-label="Light switch"><span class="fa fa-sun"></span></button>
  <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdown-lightswitch">
<li><button class="dropdown-item" data-bs-theme-value="light"><span class="fa fa-sun"></span> Light</button></li>
    <li><button class="dropdown-item" data-bs-theme-value="dark"><span class="fa fa-moon"></span> Dark</button></li>
    <li><button class="dropdown-item" data-bs-theme-value="auto"><span class="fa fa-adjust"></span> Auto</button></li>
  </ul>
</li>
      </ul>
</div>


  </div>
</nav><div class="container template-quarto">
<div class="row">
  <main id="main" class="col-md-9"><div class="page-header">

      <h1>Random Forest Classification with ggRandomForests</h1>

      <p class="author">John Ehrlinger</p>
      <p class="date">2026-07-16</p>

      <small class="dont-index">Source: <a href="https://github.com/ehrlinger/ggRandomForests/blob/main/vignettes/ggRandomForests-classification.qmd" class="external-link"><code>vignettes/ggRandomForests-classification.qmd</code></a></small>
      <div class="d-none name"><code></code></div>
    </div>






    <div>
<blockquote>
<p><strong>Work in progress</strong></p>
<p>This vignette is under active development. Code examples and narrative may change before the next release.</p>
</blockquote>
</div>
<section class="section level2"><h2 id="introduction">Introduction<a class="anchor" aria-label="anchor" href="#introduction"></a>
</h2>
<p>Random forests <span class="citation" data-cites="Breiman:2001">(<a href="#ref-Breiman:2001" role="doc-biblioref">Breiman 2001</a>)</span> are a non-parametric ensemble method that requires no distributional or functional assumptions on how covariates relate to the response. For classification, each tree votes for a class, and the forest reports the vote fractions as class probabilities. The <strong>randomForestSRC</strong> package <span class="citation" data-cites="Ishwaran:RFSRC:2014">(<a href="#ref-Ishwaran:RFSRC:2014" role="doc-biblioref">Ishwaran and Kogalur 2024</a>)</span> provides a unified implementation for survival, regression, and classification forests.</p>
<p><strong>ggRandomForests</strong> extracts tidy data objects from <code>rfsrc</code> fits and renders them with <strong>ggplot2</strong> <span class="citation" data-cites="Wickham:2009">(<a href="#ref-Wickham:2009" role="doc-biblioref">Wickham 2016</a>)</span>, making it straightforward to explore how a forest is constructed, which variables matter, and how the predicted probabilities depend on individual predictors.</p>
<p>This vignette demonstrates a complete random forest classification workflow on Fisher’s iris data <span class="citation" data-cites="Fisher:1936">(<a href="#ref-Fisher:1936" role="doc-biblioref">Fisher 1936</a>)</span>:</p>
<ol type="1">
<li>
<strong>Data exploration</strong> — EDA scatter panels, the two variable pairs that separate the three species</li>
<li>
<strong>Growing the forest</strong> — fitting an RF, checking OOB error convergence</li>
<li>
<strong>Variable selection</strong> — VIMP and minimal depth via <code><a href="https://www.randomforestsrc.org//reference/max.subtree.rfsrc.html" class="external-link">max.subtree()</a></code>
</li>
<li>
<strong>SHAP analysis</strong> — per-observation, per-class additive explanations via <code><a href="../reference/gg_shap.html">gg_shap()</a></code>
</li>
<li>
<strong>Dependence plots</strong> — variable dependence and partial dependence via <code><a href="../reference/gg_variable.html">gg_variable()</a></code> and <code><a href="../reference/gg_partial_rfsrc.html">gg_partial_rfsrc()</a></code>
</li>
<li>
<strong>Classification performance</strong> — ROC curves and AUC via <code><a href="../reference/gg_roc.rfsrc.html">gg_roc()</a></code>
</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org" class="external-link">ggplot2</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org" class="external-link">dplyr</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://www.randomforestsrc.org/" class="external-link">randomForestSRC</a></span><span class="op">)</span></span>
<span></span>
<span><span class="kw">if</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/ns-load.html" class="external-link">requireNamespace</a></span><span class="op">(</span><span class="st">"ggRandomForests"</span>, quietly <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/ehrlinger/ggRandomForests" class="external-link">ggRandomForests</a></span><span class="op">)</span></span>
<span><span class="op">}</span> <span class="kw">else</span> <span class="kw">if</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/ns-load.html" class="external-link">requireNamespace</a></span><span class="op">(</span><span class="st">"pkgload"</span>, quietly <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="fu">pkgload</span><span class="fu">::</span><span class="fu"><a href="https://pkgload.r-lib.org/reference/load_all.html" class="external-link">load_all</a></span><span class="op">(</span>export_all <span class="op">=</span> <span class="cn">FALSE</span>, helpers <span class="op">=</span> <span class="cn">FALSE</span>, attach_testthat <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="op">}</span> <span class="kw">else</span> <span class="op">{</span></span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/stop.html" class="external-link">stop</a></span><span class="op">(</span><span class="st">"Install ggRandomForests (or pkgload for dev builds) to render this vignette."</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/get_theme.html" class="external-link">theme_set</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html" class="external-link">theme_bw</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
</div>
</section><section class="section level2"><h2 id="data-iris-flower-measurements">Data: Iris Flower Measurements<a class="anchor" aria-label="anchor" href="#data-iris-flower-measurements"></a>
</h2>
<p>Fisher’s iris data <span class="citation" data-cites="Fisher:1936">(<a href="#ref-Fisher:1936" role="doc-biblioref">Fisher 1936</a>)</span> measures sepal and petal length and width for 150 flowers, 50 each from three species: <em>setosa</em>, <em>versicolor</em>, and <em>virginica</em>. It is a small data set, and that is a feature here, not a flaw: every figure in this vignette renders in under a second, and the structure is well-understood enough that any strange behaviour stands out.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/data.html" class="external-link">data</a></span><span class="op">(</span><span class="va">iris</span><span class="op">)</span></span></code></pre></div>
</div>
<section class="level2"><h3 id="exploratory-data-analysis">Exploratory data analysis<a class="anchor" aria-label="anchor" href="#exploratory-data-analysis"></a>
</h3>
<p>Petal measurements separate the three species almost perfectly; sepal measurements do not.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html" class="external-link">ggplot</a></span><span class="op">(</span><span class="va">iris</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html" class="external-link">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">Petal.Length</span>, y <span class="op">=</span> <span class="va">Petal.Width</span>, color <span class="op">=</span> <span class="va">Species</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html" class="external-link">geom_point</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">2</span>, alpha <span class="op">=</span> <span class="fl">0.7</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_brewer.html" class="external-link">scale_color_brewer</a></span><span class="op">(</span>palette <span class="op">=</span> <span class="st">"Set2"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure><p><img src="ggRandomForests-classification_files/figure-html/eda-petal-1.png"></p>
<figcaption>Petal length vs. petal width, colored by species.</figcaption></figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html" class="external-link">ggplot</a></span><span class="op">(</span><span class="va">iris</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html" class="external-link">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">Sepal.Length</span>, y <span class="op">=</span> <span class="va">Sepal.Width</span>, color <span class="op">=</span> <span class="va">Species</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html" class="external-link">geom_point</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">2</span>, alpha <span class="op">=</span> <span class="fl">0.7</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_brewer.html" class="external-link">scale_color_brewer</a></span><span class="op">(</span>palette <span class="op">=</span> <span class="st">"Set2"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure><p><img src="ggRandomForests-classification_files/figure-html/eda-sepal-1.png"></p>
<figcaption>Sepal length vs. sepal width, colored by species.</figcaption></figure>
</div>
</div>
</div>
<p><em>setosa</em> sits in its own corner of petal space, clean of the other two. <em>versicolor</em> and <em>virginica</em> overlap in both plots, more so on sepals than petals. Keep that overlap in mind — it is the interesting case for everything that follows, since <em>setosa</em> is trivial for the forest to get right.</p>
</section></section><section class="section level2"><h2 id="growing-a-random-forest">Growing a Random Forest<a class="anchor" aria-label="anchor" href="#growing-a-random-forest"></a>
</h2>
<p>We grow a classification forest using all four predictors. The <code><a href="https://www.randomforestsrc.org//reference/rfsrc.html" class="external-link">rfsrc()</a></code> function detects the classification family from the factor response.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html" class="external-link">set.seed</a></span><span class="op">(</span><span class="fl">42</span><span class="op">)</span></span>
<span><span class="va">rfsrc_iris</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://www.randomforestsrc.org//reference/rfsrc.html" class="external-link">rfsrc</a></span><span class="op">(</span><span class="va">Species</span> <span class="op">~</span> <span class="va">.</span>, data <span class="op">=</span> <span class="va">iris</span>,</span>
<span>                    ntree <span class="op">=</span> <span class="fl">200</span>, importance <span class="op">=</span> <span class="cn">TRUE</span>, err.block <span class="op">=</span> <span class="fl">5</span><span class="op">)</span></span>
<span><span class="va">rfsrc_iris</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code><span><span class="co">#&gt;                          Sample size: 150</span></span>
<span><span class="co">#&gt;            Frequency of class labels: setosa=50, versicolor=50, virginica=50</span></span>
<span><span class="co">#&gt;                      Number of trees: 200</span></span>
<span><span class="co">#&gt;            Forest terminal node size: 1</span></span>
<span><span class="co">#&gt;        Average no. of terminal nodes: 9.75</span></span>
<span><span class="co">#&gt; No. of variables tried at each split: 2</span></span>
<span><span class="co">#&gt;               Total no. of variables: 4</span></span>
<span><span class="co">#&gt;        Resampling used to grow trees: swor</span></span>
<span><span class="co">#&gt;     Resample size used to grow trees: 95</span></span>
<span><span class="co">#&gt;                             Analysis: RF-C</span></span>
<span><span class="co">#&gt;                               Family: class</span></span>
<span><span class="co">#&gt;                       Splitting rule: gini *random*</span></span>
<span><span class="co">#&gt;        Number of random split points: 10</span></span>
<span><span class="co">#&gt;                    (OOB) Brier score: 0.02253931</span></span>
<span><span class="co">#&gt;         (OOB) Normalized Brier score: 0.10142687</span></span>
<span><span class="co">#&gt;                            (OOB) AUC: 0.994</span></span>
<span><span class="co">#&gt;                       (OOB) Log-loss: 0.11724994</span></span>
<span><span class="co">#&gt;    (OOB) Requested performance error: 0.04, 0, 0.06, 0.06</span></span>
<span><span class="co">#&gt;</span></span>
<span><span class="co">#&gt; Confusion matrix:</span></span>
<span><span class="co">#&gt;</span></span>
<span><span class="co">#&gt;             predicted</span></span>
<span><span class="co">#&gt;   observed   setosa versicolor virginica class.error</span></span>
<span><span class="co">#&gt;   setosa         50          0         0        0.00</span></span>
<span><span class="co">#&gt;   versicolor      0         47         3        0.06</span></span>
<span><span class="co">#&gt;   virginica       0          3        47        0.06</span></span>
<span><span class="co">#&gt;</span></span>
<span><span class="co">#&gt;       (OOB) Misclassification rate: 0.04</span></span>
<span><span class="co">#&gt;</span></span>
<span><span class="co">#&gt; Random-classifier baselines (uniform):</span></span>
<span><span class="co">#&gt;    Brier: 0.22222222   Normalized Brier: 1   Log-loss: 1.09861229</span></span></code></pre>
</div>
</div>
<p>The forest grew 200 trees. The confusion matrix confirms what the EDA suggested: every <em>setosa</em> is classified correctly, while <em>versicolor</em> and <em>virginica</em> trade three misclassifications each way, for an overall OOB misclassification rate of 4%.</p>
<section class="level2"><h3 id="oob-error-convergence">OOB error convergence<a class="anchor" aria-label="anchor" href="#oob-error-convergence"></a>
</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot</a></span><span class="op">(</span><span class="fu"><a href="../reference/gg_error.html">gg_error</a></span><span class="op">(</span><span class="va">rfsrc_iris</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure><p><img src="ggRandomForests-classification_files/figure-html/error-plot-1.png"></p>
<figcaption>OOB misclassification rate vs. number of trees, overall and per class.</figcaption></figure>
</div>
</div>
</div>
<p>The <em>setosa</em> error drops to zero almost immediately. <em>versicolor</em> and <em>virginica</em> settle in around 6% each, and the overall rate levels off near 4% well before 200 trees — the forest is not still learning by the time we stop growing it.</p>
</section><section class="level2"><h3 id="oob-predictions">OOB predictions<a class="anchor" aria-label="anchor" href="#oob-predictions"></a>
</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot</a></span><span class="op">(</span><span class="fu"><a href="../reference/gg_rfsrc.rfsrc.html">gg_rfsrc</a></span><span class="op">(</span><span class="va">rfsrc_iris</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure><p><img src="ggRandomForests-classification_files/figure-html/rfsrc-predicted-1.png"></p>
<figcaption>OOB predicted class probabilities, faceted by the flower’s true species.</figcaption></figure>
</div>
</div>
</div>
<p>Each panel is one true species; each point is one flower’s predicted probability for one of the three classes. <em>setosa</em> flowers pin their probability at 1 for <em>setosa</em> and 0 for the other two — no ambiguity at all. The <em>versicolor</em> and <em>virginica</em> panels show real spread: most flowers are still classified confidently, but a handful sit in the 0.2–0.6 range where the forest is genuinely unsure which of the two they are.</p>
</section></section><section class="section level2"><h2 id="variable-selection">Variable Selection<a class="anchor" aria-label="anchor" href="#variable-selection"></a>
</h2>
<section class="level2"><h3 id="variable-importance-vimp">Variable importance (VIMP)<a class="anchor" aria-label="anchor" href="#variable-importance-vimp"></a>
</h3>
<p>VIMP, computed by <a href="https://www.randomforestsrc.org" class="external-link">randomForestSRC</a>, measures the increase in OOB prediction error when a variable’s values are randomly permuted across the out-of-bag observations <span class="citation" data-cites="Breiman:2001">(<a href="#ref-Breiman:2001" role="doc-biblioref">Breiman 2001</a>)</span>. For a classification forest, <code><a href="../reference/gg_vimp.html">gg_vimp()</a></code> returns one column per class alongside the overall score, and <code><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot()</a></code> facets on that automatically.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot</a></span><span class="op">(</span><span class="fu"><a href="../reference/gg_vimp.html">gg_vimp</a></span><span class="op">(</span><span class="va">rfsrc_iris</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure><p><img src="ggRandomForests-classification_files/figure-html/vimp-plot-1.png"></p>
<figcaption>VIMP ranking, overall and per class.</figcaption></figure>
</div>
</div>
</div>
<p><code>Petal.Length</code> and <code>Petal.Width</code> dominate every facet, <code>Sepal.Length</code> and <code>Sepal.Width</code> barely register — consistent with the EDA. Look closely at the <em>virginica</em> facet: <code>Sepal.Length</code> has a small negative VIMP there (colored differently), meaning permuting it very slightly <em>helped</em> virginica predictions in this fit. That kind of disagreement across facets is exactly what a per-class VIMP breakdown is for; a single overall score would have hidden it. (This is a distinct question from the permutation-vs-varPro comparison covered in <code><a href="../articles/varpro.html">vignette("varpro", package = "ggRandomForests")</a></code>, which contrasts <em>how</em> importance is measured rather than <em>for which class</em>.)</p>
</section><section class="level2"><h3 id="minimal-depth">Minimal depth<a class="anchor" aria-label="anchor" href="#minimal-depth"></a>
</h3>
<p>Minimal depth <span class="citation" data-cites="Ishwaran:2010">(<a href="#ref-Ishwaran:2010" role="doc-biblioref">Ishwaran et al. 2010</a>)</span> ranks variables by how close to the root node they first split, on average.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">md_iris</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://www.randomforestsrc.org//reference/max.subtree.rfsrc.html" class="external-link">max.subtree</a></span><span class="op">(</span><span class="va">rfsrc_iris</span><span class="op">)</span></span></code></pre></div>
</div>
<p>The threshold is 1.88, selecting 2 variables: Petal.Length, Petal.Width. VIMP and minimal depth agree.</p>
</section></section><section class="section level2"><h2 id="shap-analysis">SHAP Analysis<a class="anchor" aria-label="anchor" href="#shap-analysis"></a>
</h2>
<p>VIMP ranks importance averaged over the whole forest, and it does not change with the question you ask. SHAP does: a classification forest predicts one probability per class, and <code><a href="../reference/gg_shap.html">gg_shap()</a></code> explains exactly one of those probabilities at a time, chosen with the <code>which.class</code> argument. Ask for class 1 (<em>setosa</em>) and you get contributions to the <em>setosa</em> probability; switch to class 3 (<em>virginica</em>) and every contribution is recomputed for <em>virginica</em> instead. Nothing else about the method changes — same players, same game, different payout to split.</p>
<p>We target <em>virginica</em> (<code>which.class = 3</code>), the harder of the two overlapping species. With only four predictors, <code>kernelshap</code> runs in exact mode, so explaining all 150 flowers takes about two seconds — no need for the random-sample workaround the regression vignette uses on the larger, higher- dimensional Boston housing data.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html" class="external-link">set.seed</a></span><span class="op">(</span><span class="fl">43</span><span class="op">)</span></span>
<span><span class="va">gg_shp</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/gg_shap.html">gg_shap</a></span><span class="op">(</span><span class="va">rfsrc_iris</span>, bg_n <span class="op">=</span> <span class="fl">50</span>, which.class <span class="op">=</span> <span class="fl">3</span><span class="op">)</span></span></code></pre></div>
</div>
<section class="level2"><h3 id="shap-importance">SHAP importance<a class="anchor" aria-label="anchor" href="#shap-importance"></a>
</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot</a></span><span class="op">(</span><span class="va">gg_shp</span>, type <span class="op">=</span> <span class="st">"importance"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure><p><img src="ggRandomForests-classification_files/figure-html/shap-importance-plot-1.png"></p>
<figcaption>Mean absolute SHAP value per predictor, virginica probability.</figcaption></figure>
</div>
</div>
</div>
<p>Same two variables on top as VIMP and minimal depth, <code>Petal.Length</code> ahead of <code>Petal.Width</code>. Three different mechanisms, one answer for the dominant variables — the disagreement worth watching for is further down the ranking, not at the top.</p>
</section><section class="level2"><h3 id="shap-beeswarm">SHAP beeswarm<a class="anchor" aria-label="anchor" href="#shap-beeswarm"></a>
</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot</a></span><span class="op">(</span><span class="va">gg_shp</span>, type <span class="op">=</span> <span class="st">"beeswarm"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure><p><img src="ggRandomForests-classification_files/figure-html/shap-beeswarm-plot-1.png"></p>
<figcaption>SHAP beeswarm for virginica probability: every dot is one flower’s contribution for one predictor.</figcaption></figure>
</div>
</div>
</div>
<p><code>Petal.Width</code> shows a clean gradient: the yellow (wide petal) dots sit on the positive side, pushing the predicted <em>virginica</em> probability up; the purple (narrow petal) dots sit on the negative side, pulling it down. That is exactly what you would expect from the EDA scatter — <em>virginica</em> has the widest petals of the three species.</p>
</section><section class="level2"><h3 id="shap-dependence">SHAP dependence<a class="anchor" aria-label="anchor" href="#shap-dependence"></a>
</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot</a></span><span class="op">(</span><span class="va">gg_shp</span>, type <span class="op">=</span> <span class="st">"dependence"</span>, xvar <span class="op">=</span> <span class="st">"Petal.Width"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure><p><img src="ggRandomForests-classification_files/figure-html/shap-dependence-plot-1.png"></p>
<figcaption>SHAP dependence for Petal.Width, virginica probability.</figcaption></figure>
</div>
</div>
</div>
<p>The upward slope states the same relationship as a number instead of a color: as <code>Petal.Width</code> increases, its contribution to the <em>virginica</em> probability climbs from clearly negative to clearly positive, crossing zero around the point where <em>versicolor</em> and <em>virginica</em> petals start to overlap in the EDA plot.</p>
</section></section><section class="section level2"><h2 id="variable-dependence">Variable Dependence<a class="anchor" aria-label="anchor" href="#variable-dependence"></a>
</h2>
<section class="level2"><h3 id="variable-dependence-plots">Variable dependence plots<a class="anchor" aria-label="anchor" href="#variable-dependence-plots"></a>
</h3>
<p>Variable dependence shows each flower’s OOB predicted class probability plotted against a predictor. For a classification forest, <code><a href="../reference/gg_variable.html">gg_variable()</a></code> returns one probability column per class and <code><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot()</a></code> facets on it, the same way <code><a href="../reference/gg_vimp.html">gg_vimp()</a></code> does.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">gg_v</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/gg_variable.html">gg_variable</a></span><span class="op">(</span><span class="va">rfsrc_iris</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot</a></span><span class="op">(</span><span class="va">gg_v</span>, xvar <span class="op">=</span> <span class="st">"Petal.Width"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure><p><img src="ggRandomForests-classification_files/figure-html/vardep-panel-1.png"></p>
<figcaption>Variable dependence for Petal.Width, faceted by predicted-class probability.</figcaption></figure>
</div>
</div>
</div>
<p>Three curves, three stories: <em>setosa</em>’s probability collapses to zero past a petal width of about 0.6, <em>versicolor</em> peaks in the middle of the range and falls off on both sides, and <em>virginica</em> rises steadily from zero starting around 1.0 — the same three-panel pattern the beeswarm and dependence plots already showed for <em>virginica</em> alone, now visible for all three classes at once.</p>
</section><section class="level2"><h3 id="partial-dependence">Partial dependence<a class="anchor" aria-label="anchor" href="#partial-dependence"></a>
</h3>
<p>Partial dependence integrates out the effects of all other covariates, giving a risk-adjusted view of each predictor’s marginal effect on one class’s predicted probability <span class="citation" data-cites="Friedman:2000">(<a href="#ref-Friedman:2000" role="doc-biblioref">Friedman 2001</a>)</span>. Unlike <code><a href="../reference/gg_shap.html">gg_shap()</a></code>, <code><a href="../reference/gg_partial_rfsrc.html">gg_partial_rfsrc()</a></code> has no <code>which.class</code> argument for classification forests; it defers to <code><a href="https://www.randomforestsrc.org//reference/partial.rfsrc.html" class="external-link">randomForestSRC::partial.rfsrc()</a></code>’s own default, which targets the first factor level, <em>setosa</em> here.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">pd</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/gg_partial_rfsrc.html">gg_partial_rfsrc</a></span><span class="op">(</span><span class="va">rfsrc_iris</span>, xvar.names <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="st">"Petal.Length"</span>, <span class="st">"Petal.Width"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot</a></span><span class="op">(</span><span class="va">pd</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure><p><img src="ggRandomForests-classification_files/figure-html/partial-dep-1.png"></p>
<figcaption>Partial dependence for petal measurements, setosa probability.</figcaption></figure>
</div>
</div>
</div>
<p>Both curves fall sharply and then flatten near zero — the risk-adjusted version of what the EDA already showed: past a certain petal size, a flower is essentially never <em>setosa</em>. Getting the same kind of curve for <em>versicolor</em> or <em>virginica</em> instead means going back to <code><a href="../reference/gg_shap.html">gg_shap()</a></code>: re-run it with <code>which.class = 2</code> or <code>3</code>, then <code><a href="../reference/shap_dependence.html">shap_dependence()</a></code> on that new object picks up wherever <code>which.class</code> left off.</p>
</section></section><section class="section level2"><h2 id="classification-performance-roc-and-auc">Classification Performance: ROC and AUC<a class="anchor" aria-label="anchor" href="#classification-performance-roc-and-auc"></a>
</h2>
<p>ROC curves and AUC have no equivalent in the regression vignette — they are specific to classification, where “how well does the forest separate this class from the rest” is itself a well-posed question. <code><a href="../reference/gg_roc.rfsrc.html">gg_roc()</a></code> computes the curve for one class at a time, indexed the same way as <code><a href="../reference/gg_shap.html">gg_shap()</a></code>’s <code>which.class</code>, just under the name <code>which_outcome</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">roc_virginica</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/gg_roc.rfsrc.html">gg_roc</a></span><span class="op">(</span><span class="va">rfsrc_iris</span>, which_outcome <span class="op">=</span> <span class="fl">3</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot</a></span><span class="op">(</span><span class="va">roc_virginica</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure><p><img src="ggRandomForests-classification_files/figure-html/roc-plot-1.png"></p>
<figcaption>ROC curve for virginica vs. the rest.</figcaption></figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="../reference/calc_auc.html">calc_auc</a></span><span class="op">(</span><span class="va">roc_virginica</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code><span><span class="co">#&gt; [1] 0.9928</span></span></code></pre>
</div>
</div>
<p>An AUC of 0.993 for <em>virginica</em> confirms the forest separates it well, even given its overlap with <em>versicolor</em>. <em>setosa</em>’s ROC curve is not worth plotting — it is a right angle, AUC 1, the geometric version of the confusion matrix’s perfect row.</p>
</section><section class="section level2"><h2 id="conclusion">Conclusion<a class="anchor" aria-label="anchor" href="#conclusion"></a>
</h2>
<p>We have walked a full random forest classification analysis with <strong>randomForestSRC</strong> and <strong>ggRandomForests</strong>, and the pieces line up:</p>
<ul>
<li>
<code><a href="../reference/gg_error.html">gg_error()</a></code> showed <em>setosa</em> converging immediately, <em>versicolor</em> and <em>virginica</em> settling near 6% each.</li>
<li>VIMP (<code><a href="../reference/gg_vimp.html">gg_vimp()</a></code>) and minimal depth (<code><a href="https://www.randomforestsrc.org//reference/max.subtree.rfsrc.html" class="external-link">max.subtree()</a></code>) agreed: <code>Petal.Length</code> and <code>Petal.Width</code> dominate, for every class.</li>
<li>
<code><a href="../reference/gg_shap.html">gg_shap()</a></code> gave the same top variables, but added something VIMP cannot: a signed, additive, per-flower contribution to one class’s probability, chosen with <code>which.class</code>.</li>
<li>
<code><a href="../reference/gg_variable.html">gg_variable()</a></code> and <code><a href="../reference/gg_partial_rfsrc.html">gg_partial_rfsrc()</a></code> traced the marginal and risk-adjusted versions of the same curves the SHAP dependence plot already hinted at.</li>
<li>
<code><a href="../reference/gg_roc.rfsrc.html">gg_roc()</a></code> and <code><a href="../reference/calc_auc.html">calc_auc()</a></code> closed the loop with the classification-specific question SHAP and VIMP do not answer directly: how well does the forest separate each class from the rest.</li>
</ul>
<p>The pattern from the regression vignette holds here too. Each <code>gg_*()</code> function returns a tidy object; the plotting is a separate step. Use the package’s <code><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot()</a></code> methods when the default figure is what you want, and reach for <code>ggplot2</code> directly when it is not.</p>
</section><section class="section level2"><h2 class="unnumbered" id="references">References<a class="anchor" aria-label="anchor" href="#references"></a>
</h2>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-Breiman:2001" class="csl-entry" role="listitem">
Breiman, Leo. 2001. <span>“Random Forests.”</span> <em>Machine Learning</em> 45 (1): 5–32. <a href="https://doi.org/10.1023/A:1010933404324" class="external-link">https://doi.org/10.1023/A:1010933404324</a>.
</div>
<div id="ref-Fisher:1936" class="csl-entry" role="listitem">
Fisher, Ronald A. 1936. <span>“The Use of Multiple Measurements in Taxonomic Problems.”</span> <em>Annals of Eugenics</em> 7 (2): 179–88. <a href="https://doi.org/10.1111/j.1469-1809.1936.tb02137.x" class="external-link">https://doi.org/10.1111/j.1469-1809.1936.tb02137.x</a>.
</div>
<div id="ref-Friedman:2000" class="csl-entry" role="listitem">
Friedman, Jerome H. 2001. <span>“Greedy Function Approximation: A Gradient Boosting Machine.”</span> <em>The Annals of Statistics</em> 29 (5): 1189–232. <a href="https://doi.org/10.1214/aos/1013203451" class="external-link">https://doi.org/10.1214/aos/1013203451</a>.
</div>
<div id="ref-Ishwaran:RFSRC:2014" class="csl-entry" role="listitem">
Ishwaran, Hemant, and Udaya B. Kogalur. 2024. <em><span class="nocase">randomForestSRC</span>: Fast Unified Random Forests for Survival, Regression, and Classification (<span>RF-SRC</span>)</em>. <a href="https://cran.r-project.org/package=randomForestSRC" class="external-link">https://cran.r-project.org/package=randomForestSRC</a>.
</div>
<div id="ref-Ishwaran:2010" class="csl-entry" role="listitem">
Ishwaran, Hemant, Udaya B. Kogalur, Eiran Z. Gorodeski, Andy J. Minn, and Michael S. Lauer. 2010. <span>“High-Dimensional Variable Selection for Survival Data.”</span> <em>Journal of the American Statistical Association</em> 105 (489): 205–17. <a href="https://doi.org/10.1198/jasa.2009.tm08622" class="external-link">https://doi.org/10.1198/jasa.2009.tm08622</a>.
</div>
<div id="ref-Wickham:2009" class="csl-entry" role="listitem">
Wickham, Hadley. 2016. <em><span class="nocase">ggplot2</span>: Elegant Graphics for Data Analysis</em>. 2nd ed. Springer. <a href="https://doi.org/10.1007/978-3-319-24277-4" class="external-link">https://doi.org/10.1007/978-3-319-24277-4</a>.
</div>
</div>
</section><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'light-border',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config);
    }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script></main><aside class="col-md-3"><nav id="toc" aria-label="Table of contents"><h2>On this page</h2>
    </nav></aside>
</div>


    <footer><div class="pkgdown-footer-left">
  <p>John Ehrlinger</p>
</div>

<div class="pkgdown-footer-right">
  <p>Built with <a href="https://pkgdown.r-lib.org/" class="external-link">pkgdown</a></p>
</div>

    </footer>
</div>





  </body>
</html>
